stt742, sc68468

**Part 1: Data Transformation**

In [70]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from datetime import datetime
from dateutil import parser

In [71]:
file_path = 'gs://adult_income_cs329e/prim/adult.csv'
adult = pd.read_csv(file_path, encoding='latin-1')
adult.columns = ['age', 'workclass', 'fnlwght', 'education',
'education_num', 'marital_status', 'occupation', 'relationship', 'race', 'sex',
'capital_gain', 'capital_loss', 'hours_per_week', 'native_country', 'income']

In [72]:
file_path = 'gs://adult_income_cs329e/suppl/countries of the world.csv'
sup_countries = pd.read_csv(file_path, encoding='latin-1')
sup_countries.columns = ['country', 'region', 'population', 'area', 'population_density', 'coastline',
'net_migration', 'infant_mortality', 'gdp_per_capita', 'literacy', 'phone', 'arable', 'crops', 'other',
 'climate', 'birthrate', 'deathrate', 'agriculture', 'industry', 'service']

In [73]:
adult.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwght         32561 non-null  int64
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [74]:
sup_countries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 227 entries, 0 to 226
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   country             227 non-null    object
 1   region              227 non-null    object
 2   population          227 non-null    int64
 3   area                227 non-null    int64
 4   population_density  227 non-null    object
 5   coastline           227 non-null    object
 6   net_migration       224 non-null    object
 7   infant_mortality    224 non-null    object
 8   gdp_per_capita      226 non-null    float64
 9   literacy            209 non-null    object
 10  phone               223 non-null    object
 11  arable              225 non-null    object
 12  crops               225 non-null    object
 13  other               225 non-null    object
 14  climate             205 non-null    object
 15  birthrate           224 non-null    object
 16  deathrate           223 non-null    object
 17  agriculture         212 non-null    object
 18  industry            211 non-null    object
 19  service             212 non-null    object
dtypes: float64(1), int64(2), object(17)
memory usage: 35.6+ KB

##### Print a random row from each of the DataFrames to see a concrete example:

In [75]:
adult.sample()

,age,workclass,fnlwght,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
27920,58,?,150031,Some-college,10,Never-married,?,Not-in-family,White,Female,0,0,40,United-States,<=50K

In [76]:
sup_countries.sample()

,country,region,population,area,population_density,coastline,net_migration,infant_mortality,gdp_per_capita,literacy,phone,arable,crops,other,climate,birthrate,deathrate,agriculture,industry,service
41,Chile,LATIN AMER. & CARIB,16134219,756950,"21,3","0,85",0,"8,8",9900.0,"96,2","213,0","2,65","0,42","96,93",3,"15,23","5,81","0,06","0,493","0,447"

### Transform features

 **adult dataset**: We've identified features that would benefit from being formatted appropriately: sex and income. These variables are encoded as objects in Python. They will be easier to analyze and perform aggregations on as numeric values.

sex

In [77]:
adult['sex'].unique()

array(['Female', 'Male'], dtype=object)

In [78]:
adult['sex'] = adult['sex'].astype(str)
map_estimates_to_numeric = {'Female': 0, 'Male': 1}

In [79]:
adult['sex'] = adult['sex'].map(map_estimates_to_numeric)

In [80]:
np.sort(adult['sex'].unique())

array([0, 1])

income

In [81]:
adult['income'].unique()

array(['<=50K', '>50K'], dtype=object)

In [82]:
adult['income'] = adult['income'].astype(str)
map_estimates_to_numeric = {'<=50K': 0, '>50K': 1}

In [83]:
adult['income'] = adult['income'].map(map_estimates_to_numeric)

In [84]:
np.sort(adult['income'].unique())

array([0, 1])

### Transform features

 **supp_countries dataset**: We've identified features that would benefit from appropriate formatting: population_density, literacy, agriculture, industry, and service. These variables are encoded as objects in Python. They will be easier to analyze and perform aggregations on as numeric values.

population_density

In [85]:
sup_countries['population_density'].unique()

array(['48,0', '124,6', '13,8', '290,4', '152,1', '9,7', '132,1', '156,0',
       '14,4', '99,9', '372,5', '2,6', '97,7', '91,9', '21,8', '1050,5',
       '1023,4', '649,5', '49,6', '340,0', '12,5', '69,8', '1241,0',
       '48,5', '8,2', '88,0', '2,7', '22,1', '151,0', '65,8', '66,6',
       '50,7', '290,7', '76,7', '36,5', '3,3', '104,4', '173,4', '6,9',
       '7,7', '21,3', '136,9', '38,3', '318,4', '26,7', '10,8', '89,1',
       '79,8', '54,8', '79,5', '102,7', '84,8', '129,8', '126,5', '21,2',
       '91,4', '188,5', '70,8', '47,8', '78,8', '324,3', '19,3', '39,5',
       '29,3', '66,3', '33,8', '15,5', '111,3', '2,2', '65,9', '5,3',
       '145,3', '3968,8', '66,9', '230,9', '93,6', '3989,7', '81,0',
       '0,0', '260,8', '254,4', '316,1', '112,9', '838,6', '39,4', '39,9',
       '3,6', '299,4', '65,4', '6355,7', '107,3', '2,9', '333,2', '127,9',
       '41,7', '61,3', '57,8', '131,9', '305,8', '193,0', '250,9',
       '337,4', '785,2', '64,0', '5,6', '59,6', '130,0', '191,8', '496,0',
       '135,7', '26,3', '26,9', '35,2', '27,3', '3,4', '212,4', '55,0',
       '183,5', '16183,0', '80,9', '31,7', '109,8', '74,0', '1196,7',
       '9,5', '1266,5', '5,1', '396,5', '3,1', '608,3', '538,1', '54,5',
       '153,9', '132,0', '16271,5', '1,8', '92,5', '74,4', '24,6', '2,5',
       '632,7', '192,2', '397,1', '231,0', '11,5', '15,2', '43,0', '9,9',
       '142,7', '172,9', '14,2', '14,6', '206,2', '44,9', '40,8', '12,3',
       '16,0', '22,0', '298,2', '123,3', '114,8', '284,8', '77,4',
       '312,9', '93,9', '8,4', '328,4', '18,2', '149,9', '273,5', '29,0',
       '303,0', '60,1', '479,5', '193,2', '61,1', '106,3', '179,2',
       '83,7', '6482,2', '111,4', '99,2', '19,4', '13,9', '36,2', '80,0',
       '308,2', '16,5', '65,5', '20,0', '182,2', '102,0', '640,3', '51,2',
       '39,6', '125,7', '153,3', '207,9', '62,2', '90,2', '10,3', '49,2',
       '454,2', '119,5', '31,4', '247,6', '31,0', '19,5', '61,0', '17,1',
       '28,2', '256,1', '56,9', '58,5', '419,9', '1,0', '40,6', '15,3',
       '31,3'], dtype=object)

In [86]:
sup_countries['population_density'] = (sup_countries['population_density'].str.replace(',', '.', regex=False).astype(float))

Literacy

In [87]:
sup_countries['literacy'].unique()

array(['36,0', '86,5', '70,0', '97,0', '100,0', '42,0', '95,0', '89,0',
       '97,1', '98,6', '98,0', '95,6', '89,1', '43,1', '97,4', '99,6',
       '94,1', '40,9', '42,2', '87,2', nan, '79,8', '86,4', '97,8',
       '93,9', '26,6', '85,3', '51,6', '69,4', '79,0', '76,6', '51,0',
       '47,5', '96,2', '90,9', '92,5', '56,5', '65,5', '83,8', '96,0',
       '50,9', '98,5', '97,6', '99,9', '67,9', '94,0', '84,7', '58,6',
       '57,7', '80,2', '85,7', '99,8', '42,7', '93,7', '99,0', '83,0',
       '63,2', '40,1', '74,8', '97,5', '90,0', '70,6', '35,9', '42,4',
       '98,8', '52,9', '76,2', '93,5', '99,4', '59,5', '87,9', '79,4',
       '40,4', '95,4', '91,3', '98,4', '85,1', '97,9', '83,5', '66,4',
       '87,4', '84,8', '57,5', '82,6', '94,5', '68,9', '62,7', '88,7',
       '97,2', '46,4', '92,8', '97,7', '41,7', '85,6', '92,2', '99,1',
       '51,7', '47,8', '84,0', '45,2', '96,7', '91,0', '67,5', '17,6',
       '68,0', '75,8', '45,7', '92,0', '92,6', '64,6', '93,3', '82,5',
       '88,9', '70,4', '67,0', '99,7', '79,3', '78,8', '40,2', '93,0',
       '58,0', '31,4', '37,8', '92,3', '61,1', '81,6', '76,9', '96,1',
       '78,2', '60,9', '74,2', '69,9', '77,9', '99,3', '53,0', '93,4',
       '90,3', '50,0', '50,2', '80,6', '90,7'], dtype=object)

In [88]:
sup_countries['literacy'] = (sup_countries['literacy'].str.replace(',', '.', regex=False).astype(float))

Agriculture

In [89]:
sup_countries['agriculture'].unique()

array(['0,38', '0,232', '0,101', nan, '0,096', '0,04', '0,038', '0,095',
       '0,239', '0,004', '0,018', '0,141', '0,03', '0,005', '0,199',
       '0,06', '0,093', '0,01', '0,142', '0,316', '0,258', '0,128',
       '0,024', '0,084', '0,036', '0,322', '0,564', '0,463', '0,35',
       '0,448', '0,022', '0,121', '0,014', '0,55', '0,335', '0,125',
       '0,4', '0,062', '0,151', '0,088', '0,279', '0,07', '0,055',
       '0,037', '0,034', '0,179', '0,177', '0,112', '0,085', '0,149',
       '0,099', '0,102', '0,475', '0,27', '0,089', '0,028', '0,066',
       '0,031', '0,061', '0,308', '0,172', '0,009', '0,366', '0,054',
       '0,15', '0,227', '0,237', '0,62', '0,37', '0,28', '0,139', '0,001',
       '0,086', '0,186', '0,134', '0,116', '0,073', '0,05', '0,026',
       '0,021', '0,049', '0,017', '0,033', '0,067', '0,163', '0,3',
       '0,353', '0,455', '0,12', '0,769', '0,076', '0,118', '0,276',
       '0,342', '0,2', '0,45', '0,317', '0,25', '0,059', '0,289', '0,213',
       '0,17', '0,206', '0,217', '0,262', '0,097', '0,043', '0,165',
       '0,39', '0,269', '0,027', '0,216', '0,068', '0,224', '0,08',
       '0,144', '0,053', '0,002', '0,401', '0,035', '0,1', '0,114',
       '0,167', '0,166', '0,032', '0,49', '0', '0,42', '0,65', '0,025',
       '0,178', '0,387', '0,13', '0,119', '0,011', '0,015', '0,249',
       '0,234', '0,432', '0,395', '0,23', '0,007', '0,132', '0,117',
       '0,209', '0,311', '0,187', '0,26', '0,09', '0,135', '0,22'],
      dtype=object)

In [90]:
sup_countries['agriculture'] = (sup_countries['agriculture'].str.replace(',', '.', regex=False).astype(float))

Industry

In [91]:
sup_countries['industry'].unique()

array(['0,24', '0,188', '0,6', nan, '0,658', '0,18', '0,22', '0,358',
       '0,343', '0,333', '0,262', '0,304', '0,457', '0,07', '0,387',
       '0,198', '0,16', '0,316', '0,152', '0,138', '0,1', '0,379',
       '0,352', '0,308', '0,469', '0,4', '0,062', '0,561', '0,196',
       '0,082', '0,203', '0,3', '0,17', '0,294', '0,219', '0,032', '0,2',
       '0,259', '0,493', '0,473', '0,342', '0,04', '0,11', '0,57',
       '0,096', '0,299', '0,171', '0,261', '0,393', '0,246', '0,225',
       '0,328', '0,306', '0,231', '0,312', '0,357', '0,302', '0,906',
       '0,254', '0,099', '0,135', '0,295', '0,214', '0,156', '0,19',
       '0,592', '0,142', '0,283', '0,275', '0,296', '0,213', '0,362',
       '0,12', '0,092', '0,15', '0,276', '0,458', '0,424', '0,666',
       '0,46', '0,13', '0,317', '0,291', '0,337', '0,258', '0,02',
       '0,287', '0,386', '0,242', '0,34', '0,403', '0,479', '0,208',
       '0,21', '0,443', '0,054', '0,499', '0,39', '0,325', '0,072',
       '0,319', '0,165', '0,158', '0,48', '0,23', '0,149', '0,29',
       '0,298', '0,233', '0,348', '0,315', '0,244', '0,088', '0,273',
       '0,487', '0,415', '0,251', '0,381', '0,207', '0,27', '0,326',
       '0,311', '0,274', '0,45', '0,801', '0,35', '0,371', '0,229',
       '0,26', '0,584', '0,148', '0,613', '0,209', '0,255', '0,31',
       '0,339', '0,369', '0,303', '0,515', '0,282', '0,286', '0,172',
       '0,441', '0,204', '0,318', '0,38', '0,272', '0,222', '0,452',
       '0,585', '0,237', '0,419', '0,41', '0,28', '0,472', '0,243'],
      dtype=object)

In [92]:
sup_countries['industry'] = (sup_countries['industry'].str.replace(',', '.', regex=False).astype(float))

Service

In [93]:
sup_countries['service'].unique()

array(['0,38', '0,579', '0,298', nan, '0,246', '0,78', '0,743', '0,547',
       '0,418', '0,663', '0,7', '0,678', '0,402', '0,9', '0,608', '0,603',
       '0,591', '0,749', '0,612', '0,546', '0,89', '0,363', '0,52',
       '0,55', '0,507', '0,516', '0,92', '0,403', '0,482', '0,353',
       '0,334', '0,35', '0,382', '0,684', '0,66', '0,954', '0,25',
       '0,406', '0,447', '0,533', '0,56', '0,34', '0,369', '0,753',
       '0,614', '0,622', '0,765', '0,573', '0,735', '0,596', '0,495',
       '0,582', '0,618', '0,493', '0,599', '0,062', '0,643', '0,666',
       '0,426', '0,62', '0,776', '0,676', '0,764', '0,778', '0,769',
       '0,348', '0,549', '0,687', '0,553', '0,695', '0,387', '0,733',
       '0,766', '0,68', '0,585', '0,87', '0,401', '0,26', '0,427',
       '0,906', '0,651', '0,538', '0,408', '0,46', '0,261', '0,49',
       '0,86', '0,657', '0,688', '0,615', '0,725', '0,93', '0,668',
       '0,36', '0,563', '0,439', '0,258', '0,699', '0,67', '0,394',
       '0,177', '0,425', '0,927', '0,559', '0,499', '0,436', '0,74',
       '0,534', '0,83', '0,702', '0,555', '0,58', '0,39', '0,588', '0,41',
       '0,736', '0,84', '0,762', '0,44', '0,244', '0,564', '0,583',
       '0,818', '0,266', '0,569', '0,65', '0,53', '0,64', '0,673', '0,54',
       '0,197', '0,73', '0,575', '0,37', '0,707', '0,302', '0,354',
       '0,619', '0,665', '0,21', '0,661', '0,672', '0,47', '0,671',
       '0,545', '0,366', '0,645', '0,519', '0,723', '0,48', '0,396',
       '0,5', '0,423', '0,411', '0,562', '0,469', '0,361', '0,375',
       '0,758', '0,787', '0,43', '0,541', '0,381', '0,8', '0,63', '0,4',
       '0,393', '0,489'], dtype=object)

In [94]:
sup_countries['service'] = (sup_countries['service'].str.replace(',', '.', regex=False).astype(float))

##Part 2: Missing Values and Smoothing

**adult dataset**: We decided only to use workclass, race, sex, native_country income, education_num, and hours_per_week for this dataset

In [95]:
adult_new = adult[['workclass', 'race', 'sex', 'native_country', 'income', 'education_num', 'hours_per_week']].copy()

In [96]:
adult_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   workclass       32561 non-null  object
 1   race            32561 non-null  object
 2   sex             32561 non-null  int64
 3   native_country  32561 non-null  object
 4   income          32561 non-null  int64
 5   education_num   32561 non-null  int64
 6   hours_per_week  32561 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.7+ MB

**sup_countries dataset**: We decided only to use country, population_density, literacy, agriculture, industry, service for this dataset.

In [97]:
countries_new = sup_countries[['country', 'region', 'population_density', 'literacy', 'agriculture', 'industry', 'service']].copy()

In [98]:
countries_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 227 entries, 0 to 226
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   country             227 non-null    object
 1   region              227 non-null    object
 2   population_density  227 non-null    float64
 3   literacy            209 non-null    float64
 4   agriculture         212 non-null    float64
 5   industry            211 non-null    float64
 6   service             212 non-null    float64
dtypes: float64(5), object(2)
memory usage: 12.5+ KB

Check for missing values

**adult_new dataset**: In our new dataset, only workclass and native_country have missing values as stated in the metadata

workclass:

In [99]:
adult_new['workclass'].unique()

array(['?', 'Private', 'State-gov', 'Federal-gov', 'Self-emp-not-inc',
       'Self-emp-inc', 'Local-gov', 'Without-pay', 'Never-worked'],
      dtype=object)

In [100]:
#check for number of missing values
print((adult_new['workclass'] == '?').sum())

1836

In [101]:
adult_new = adult_new[adult_new['workclass'] != '?']
#check
print((adult_new['workclass'] == '?').sum())

0

We will drop the missing values since they only make up just above 5% (1836/32561) of the dataset, dropping them would not compromise the statistical significance of the data set

native_country:

In [102]:
adult_new['native_country'].unique()

array(['United-States', '?', 'Mexico', 'Greece', 'Vietnam', 'China',
       'Taiwan', 'India', 'Philippines', 'Trinadad&Tobago', 'Canada',
       'South', 'Holand-Netherlands', 'Puerto-Rico', 'Poland', 'Iran',
       'England', 'Germany', 'Italy', 'Japan', 'Hong', 'Honduras', 'Cuba',
       'Ireland', 'Cambodia', 'Peru', 'Nicaragua', 'Dominican-Republic',
       'Haiti', 'Hungary', 'Columbia', 'Guatemala', 'El-Salvador',
       'Jamaica', 'Ecuador', 'France', 'Yugoslavia', 'Portugal', 'Laos',
       'Thailand', 'Outlying-US(Guam-USVI-etc)', 'Scotland'], dtype=object)

In [103]:
#check for number of missing values
print((adult_new['native_country'] == '?').sum())

556

We will drop the missing values since they only make up under 2% (583/32561) of the dataset, dropping them would not compromise the statistical significance of the data set

In [104]:
adult_new = adult_new[adult_new['native_country'] != '?']
#check
print((adult_new['native_country'] == '?').sum())

0

**countries_new dataset**: In our new dataset, agriculture, industry and service have missing values as stated in the metadata

In [105]:
countries_new = countries_new.fillna(0)

In [106]:
#check
countries_new['agriculture'].unique()

array([0.38 , 0.232, 0.101, 0.   , 0.096, 0.04 , 0.038, 0.095, 0.239,
       0.004, 0.018, 0.141, 0.03 , 0.005, 0.199, 0.06 , 0.093, 0.01 ,
       0.142, 0.316, 0.258, 0.128, 0.024, 0.084, 0.036, 0.322, 0.564,
       0.463, 0.35 , 0.448, 0.022, 0.121, 0.014, 0.55 , 0.335, 0.125,
       0.4  , 0.062, 0.151, 0.088, 0.279, 0.07 , 0.055, 0.037, 0.034,
       0.179, 0.177, 0.112, 0.085, 0.149, 0.099, 0.102, 0.475, 0.27 ,
       0.089, 0.028, 0.066, 0.031, 0.061, 0.308, 0.172, 0.009, 0.366,
       0.054, 0.15 , 0.227, 0.237, 0.62 , 0.37 , 0.28 , 0.139, 0.001,
       0.086, 0.186, 0.134, 0.116, 0.073, 0.05 , 0.026, 0.021, 0.049,
       0.017, 0.033, 0.067, 0.163, 0.3  , 0.353, 0.455, 0.12 , 0.769,
       0.076, 0.118, 0.276, 0.342, 0.2  , 0.45 , 0.317, 0.25 , 0.059,
       0.289, 0.213, 0.17 , 0.206, 0.217, 0.262, 0.097, 0.043, 0.165,
       0.39 , 0.269, 0.027, 0.216, 0.068, 0.224, 0.08 , 0.144, 0.053,
       0.002, 0.401, 0.035, 0.1  , 0.114, 0.167, 0.166, 0.032, 0.49 ,
       0.42 , 0.65 , 0.025, 0.178, 0.387, 0.13 , 0.119, 0.011, 0.015,
       0.249, 0.234, 0.432, 0.395, 0.23 , 0.007, 0.132, 0.117, 0.209,
       0.311, 0.187, 0.26 , 0.09 , 0.135, 0.22 ])

In [107]:
#check
countries_new['industry'].unique()

array([0.24 , 0.188, 0.6  , 0.   , 0.658, 0.18 , 0.22 , 0.358, 0.343,
       0.333, 0.262, 0.304, 0.457, 0.07 , 0.387, 0.198, 0.16 , 0.316,
       0.152, 0.138, 0.1  , 0.379, 0.352, 0.308, 0.469, 0.4  , 0.062,
       0.561, 0.196, 0.082, 0.203, 0.3  , 0.17 , 0.294, 0.219, 0.032,
       0.2  , 0.259, 0.493, 0.473, 0.342, 0.04 , 0.11 , 0.57 , 0.096,
       0.299, 0.171, 0.261, 0.393, 0.246, 0.225, 0.328, 0.306, 0.231,
       0.312, 0.357, 0.302, 0.906, 0.254, 0.099, 0.135, 0.295, 0.214,
       0.156, 0.19 , 0.592, 0.142, 0.283, 0.275, 0.296, 0.213, 0.362,
       0.12 , 0.092, 0.15 , 0.276, 0.458, 0.424, 0.666, 0.46 , 0.13 ,
       0.317, 0.291, 0.337, 0.258, 0.02 , 0.287, 0.386, 0.242, 0.34 ,
       0.403, 0.479, 0.208, 0.21 , 0.443, 0.054, 0.499, 0.39 , 0.325,
       0.072, 0.319, 0.165, 0.158, 0.48 , 0.23 , 0.149, 0.29 , 0.298,
       0.233, 0.348, 0.315, 0.244, 0.088, 0.273, 0.487, 0.415, 0.251,
       0.381, 0.207, 0.27 , 0.326, 0.311, 0.274, 0.45 , 0.801, 0.35 ,
       0.371, 0.229, 0.26 , 0.584, 0.148, 0.613, 0.209, 0.255, 0.31 ,
       0.339, 0.369, 0.303, 0.515, 0.282, 0.286, 0.172, 0.441, 0.204,
       0.318, 0.38 , 0.272, 0.222, 0.452, 0.585, 0.237, 0.419, 0.41 ,
       0.28 , 0.472, 0.243])

In [108]:
#check
countries_new['service'].unique()

array([0.38 , 0.579, 0.298, 0.   , 0.246, 0.78 , 0.743, 0.547, 0.418,
       0.663, 0.7  , 0.678, 0.402, 0.9  , 0.608, 0.603, 0.591, 0.749,
       0.612, 0.546, 0.89 , 0.363, 0.52 , 0.55 , 0.507, 0.516, 0.92 ,
       0.403, 0.482, 0.353, 0.334, 0.35 , 0.382, 0.684, 0.66 , 0.954,
       0.25 , 0.406, 0.447, 0.533, 0.56 , 0.34 , 0.369, 0.753, 0.614,
       0.622, 0.765, 0.573, 0.735, 0.596, 0.495, 0.582, 0.618, 0.493,
       0.599, 0.062, 0.643, 0.666, 0.426, 0.62 , 0.776, 0.676, 0.764,
       0.778, 0.769, 0.348, 0.549, 0.687, 0.553, 0.695, 0.387, 0.733,
       0.766, 0.68 , 0.585, 0.87 , 0.401, 0.26 , 0.427, 0.906, 0.651,
       0.538, 0.408, 0.46 , 0.261, 0.49 , 0.86 , 0.657, 0.688, 0.615,
       0.725, 0.93 , 0.668, 0.36 , 0.563, 0.439, 0.258, 0.699, 0.67 ,
       0.394, 0.177, 0.425, 0.927, 0.559, 0.499, 0.436, 0.74 , 0.534,
       0.83 , 0.702, 0.555, 0.58 , 0.39 , 0.588, 0.41 , 0.736, 0.84 ,
       0.762, 0.44 , 0.244, 0.564, 0.583, 0.818, 0.266, 0.569, 0.65 ,
       0.53 , 0.64 , 0.673, 0.54 , 0.197, 0.73 , 0.575, 0.37 , 0.707,
       0.302, 0.354, 0.619, 0.665, 0.21 , 0.661, 0.672, 0.47 , 0.671,
       0.545, 0.366, 0.645, 0.519, 0.723, 0.48 , 0.396, 0.5  , 0.423,
       0.411, 0.562, 0.469, 0.361, 0.375, 0.758, 0.787, 0.43 , 0.541,
       0.381, 0.8  , 0.63 , 0.4  , 0.393, 0.489])

Smoothing:

adult_new: most of the columns we use for this dataset is categorical (race, workclass, native_country,...) so we cannot smooth them. Moreover, education_nums' values are discrete measurments, so smoothing them would turn them into decimals, this might add unnecessary values to the dataset.

countries_new: this data set is not a time series data, it records different countries at a single point in time (cross-sectional), therefore smoothing is not needed for this dataset.

### Truncating Data Set

**adult_new**: set represents individuals living in the United States, and some people's native countries only appear once or twice in the data set. This could create unstable income rates or uncessary outliers in the data set. To accomodate that, we are going to truncate the data set to only take into account with more than 25 entries.

In [109]:
#check
len(adult_new)

30169

In [110]:
country_counts = adult_new['native_country'].value_counts()
filt_entry = country_counts[country_counts >= 25].index
print(len(filt_entry))
trunc_adult = adult_new[adult_new['native_country'].isin(filt_entry)].copy()

29

In [111]:
#check
len(trunc_adult)

29989

### Aggregating the Data Set
**adult_new (country) - PRIMARY **: We decided to aggregate the data set by the country because the adult data set contains individual date, but the country data set contains more general country data. We would not be able to meaningfully join the two tables without aggregating and take meaningiful statistics to compare.

**Specific Variable Decisions**

*income_rate:* Because of the conversion of income to a binary variable the mean represents the probability (or proportion) of individuals from that country earning more than $50K.

*education_num:* Education is measured in years and we aggregated by the mean to show the average education level of groups individuals in the adult set that are from other countries.

*hours_worked:* The hours worked influences the income, and averaging the hours per country helps to understand whether certain immigrant groups work more hours or if income reflects the difficulty of jobs.

In [112]:
adult_country_aggregated = trunc_adult.groupby('native_country').agg(income_rate =('income','mean'),
 avg_ed =('education_num','mean'),
 avg_hrs=('hours_per_week','mean'),
 sample_size=('income','count')).reset_index()

In [113]:
#check
print(adult_country_aggregated.shape)

(29, 5)

### Joining the Datasets
Before we joined the two data sets, we had to make sure the country names in the two datasets would match each other because that is what we are joining the data sets on. To make them match we decided to strip both names in both datasets, remove any &/"and", and remove any spaces or dashes. Then we joined the adult data set with the country data set as well as the aggregated adult data set with the country data set. During the join, some of the countries in the adult data set do not exist in the countries data set, 7 of them to be specific. This is because they do not exist anymore or are considered parts of other countries. The unmerged entries will be excluded from any analysis involving the merged data set.

In [114]:
#preparing for join
countries_new['country'] = (countries_new['country'].str.strip())
adult_country_aggregated['native_country'] = (adult_country_aggregated['native_country'].str.replace('-', ' ').str.replace('&', 'and').str.strip())
adult_new['native_country'] = (adult_country_aggregated['native_country'].str.replace('-', ' ').str.replace('&', 'and').str.strip())
country_fix = {
    'United-States': 'United States',
    'Puerto-Rico': 'United States',
    'El-Salvador': 'El Salvador',
    'Dominican-Republic': 'Dominican Republic',
    'Trinadad&Tobago': 'Trinidad & Tobago',
    'Holand-Netherlands': 'Netherlands',
    'Columbia': 'Colombia',
    'South': 'Korea, South',
    'Hong': 'Hong Kong',
    'Yugoslavia': 'Serbia',
    'England': 'United Kingdom',
    'Scotland': 'United Kingdom',
    'Outlying-US(Guam-USVI-etc)': 'United States',
    'United States of America' : 'United States'
}
adult_new['native_country'] = adult_new['native_country'].replace(country_fix)
adult_country_aggregated['native_country'] = adult_new['native_country'].replace(country_fix)

#join
merged_individuals = adult_new.merge(countries_new,
    left_on='native_country',
    right_on='country',
    how='left')
merged_country = adult_country_aggregated.merge(countries_new,
    left_on='native_country',
    right_on='country',
    how='inner')

In [118]:
#check
print("Unique adult countries:", trunc_adult['native_country'].nunique())
print("Unique countries dataset:", countries_new['country'].nunique())
matched = set(trunc_adult['native_country']) & set(countries_new['country'])
print("Number of matches:", len(matched))

#not matched
adult_not_matched = set(adult_new['native_country']) - set(countries_new['country'])
print(adult_not_matched)

merged_individuals

Unique adult countries: 29
Unique countries dataset: 227
Number of matches: 22
{nan}

,workclass,race,sex,native_country,income,education_num,hours_per_week,country,region,population_density,literacy,agriculture,industry,service
0,Private,White,0,China,0,9,18,China,ASIA (EX. NEAR EAST),136.9,90.9,0.125,0.473,0.403
1,Private,White,0,Cuba,0,4,40,Cuba,LATIN AMER. & CARIB,102.7,97.0,0.055,0.261,0.684
2,Private,White,0,Dominican Republic,0,10,40,Dominican Republic,LATIN AMER. & CARIB,188.5,84.7,0.112,0.306,0.582
3,Private,White,0,Ecuador,0,9,45,Ecuador,LATIN AMER. & CARIB,47.8,92.5,0.070,0.312,0.618
4,Private,White,1,El Salvador,0,6,40,El Salvador,LATIN AMER. & CARIB,324.3,80.2,0.099,0.302,0.599
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30164,Private,White,1,NaN,0,10,40,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30165,Private,White,0,NaN,0,12,38,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30166,Private,White,1,NaN,1,9,40,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30167,Private,White,0,NaN,0,9,40,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30168,Private,White,1,NaN,0,9,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Further Aggregation
**adult_new (region)**: We decided to aggregate the data set by the region because it gives a similar understanding of the data set as by country, but it does give a slightly different view allowing for deeper understanding of regional differences between immigrant groups.

In [119]:
region_agg = merged_country.groupby('region').agg(avg_income_rate=('income_rate','mean'),
    avg_literacy=('literacy','mean'),
    avg_population_density=('population_density','mean'),
    avg_agriculture=('agriculture','mean'),
    avg_industry=('industry','mean'),
    avg_service=('service','mean'),
    num_countries=('country','count')).reset_index()

In [121]:
gcspath = "gs://adult_income_cs329e/clean/merged_country.parquet"
merged_country.to_parquet(gcspath)
print("File saved to:", gcspath)

File saved to: gs://adult_income_cs329e/clean/merged_country.parquet

In [122]:
#readback
readback = pd.read_parquet(gcspath)
readback.head()

,native_country,income_rate,avg_ed,avg_hrs,sample_size,country,region,population_density,literacy,agriculture,industry,service
0,China,0.294118,11.235294,38.647059,68,China,ASIA (EX. NEAR EAST),136.9,90.9,0.125,0.473,0.403
1,Cuba,0.271739,9.695652,39.728261,92,Cuba,LATIN AMER. & CARIB,102.7,97.0,0.055,0.261,0.684
2,Dominican Republic,0.029851,7.089552,42.283582,67,Dominican Republic,LATIN AMER. & CARIB,188.5,84.7,0.112,0.306,0.582
3,Ecuador,0.148148,9.555556,40.222222,27,Ecuador,LATIN AMER. & CARIB,47.8,92.5,0.070,0.312,0.618
4,El Salvador,0.090000,6.880000,37.000000,100,El Salvador,LATIN AMER. & CARIB,324.3,80.2,0.099,0.302,0.599